# Generated by Django 2.2.5 on 2019-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
