# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_num', models.DecimalField(decimal_places=2, max_digits=2, primary_key=True, serialize=False)),
                ('author_last', models.CharField(max_length=12)),
                ('author_first', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookcode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('publisherCode', models.CharField(max_length=3)),
                ('_type', models.CharField(max_length=1)),
                ('paperback', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_num', models.DecimalField(decimal_places=2, max_digits=2, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('book_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('copyNum', models.DecimalField(decimal_places=2, max_digits=2)),
                ('quality', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=8)),
                ('branch_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publishercode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('publishername', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wrote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_num', models.DecimalField(decimal_places=2, max_digits=2)),
                ('sequence', models.DecimalField(decimal_places=2, max_digits=2)),
                ('book_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp.Copy')),
            ],
        ),
    ]
