# Generated by Django 2.2.6 on 2019-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20191014_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='authorBio',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='comment',
            name='bookComment',
            field=models.TextField(default='default'),
        ),
    ]
