# Generated by Django 2.2.6 on 2019-10-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20191014_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookPrice',
            field=models.DecimalField(decimal_places=2, default=2.22, max_digits=10),
        ),
    ]
