# Generated by Django 2.2.6 on 2019-10-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_books_bookprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookSummary',
            field=models.TextField(default='hello'),
        ),
    ]
