# Generated by Django 2.2.6 on 2019-10-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20191018_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookRating',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
