# Generated by Django 2.2.7 on 2019-11-16 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0026_auto_20191116_0112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_User',
            new_name='User_Bought',
        ),
    ]
