# Generated by Django 2.0.7 on 2019-10-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190928_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookname',
            name='author',
        ),
        migrations.RemoveField(
            model_name='booksummary',
            name='bookname',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Bookname',
        ),
        migrations.DeleteModel(
            name='Booksummary',
        ),
    ]
