# Generated by Django 2.0.7 on 2019-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='bookCovers'),
        ),
    ]
