# Generated by Django 2.2.6 on 2019-11-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20191018_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bookName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.Books'),
        ),
    ]
