# Generated by Django 2.2.6 on 2019-11-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20191101_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bookName',
            new_name='books',
        ),
    ]
