# Generated by Django 2.2.5 on 2019-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20191105_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookSales',
            field=models.IntegerField(default=0, verbose_name='Units Sold'),
        ),
    ]
