# Generated by Django 2.2.6 on 2019-10-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20191018_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publisherDate',
            field=models.CharField(default='no date', max_length=20),
        ),
    ]
