# Generated by Django 2.2.6 on 2019-10-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20191018_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookRating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=1),
        ),
    ]
