# Generated by Django 2.2.6 on 2019-10-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20191018_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookRating',
            field=models.DecimalField(decimal_places=1, default=1.2, max_digits=1),
        ),
    ]
