# Generated by Django 2.2.6 on 2019-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Book Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('genre', models.CharField(max_length=20, verbose_name='Genre')),
                ('num_sales', models.IntegerField(verbose_name='Units Sold')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
