# Generated by Django 2.2.7 on 2019-11-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_books_booksales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='authorName',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
