# Generated by Django 2.2.5 on 2019-11-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20191105_1935'),
        ('search', '0004_remove_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(default='default.jpg', on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
        ),
    ]
